// Randomized descriptions for projects
const descriptions = [
    "Works 60% of the time, every time.",
    "Warning: May cause kernel panics.",
    "Written at 3 AM. No guarantees.",
    "Not a bug, a feature.",
    "Tested on my machine. Good luck.",
    "If it crashes, you win a prize.",
    "More patches than a pirate convention.",
    "This code is held together by hope.",
    "Debugging? Never heard of it.",
    "It's not broken, it's just creatively functional.",

    "Powered by caffeine and questionable decisions.",
    "It compiled. Ship it.",
    "Works on my machine™.",
    "Somehow this passed testing.",
    "There was a plan. Once.",
    "I have absolutely no idea why this works.",
    "Documentation sold separately.",
    "Please don't ask what happens at 3 AM.",
    "Built different. Mostly incorrectly.",
    "The compiler said yes, so here we are.",

    "One does not simply fix the bug.",
    "Featuring approximately zero sensible design decisions.",
    "Runs surprisingly well considering what I did to it.",
    "Held together with duct tape and printf().",
    "Powered by raw determination.",
    "Because apparently existing solutions weren't interesting enough.",
    "A perfectly reasonable use of my free time.",
    "This seemed like a good idea at the time.",
    "Future me can deal with it.",
    "Past me is the reason this exists.",

    "May contain traces of spaghetti.",
    "Some assembly required. Literally.",
    "It was supposed to be a small project.",
    "Started as a joke. Became a problem.",
    "The README knows more than I do.",
    "No electrons were harmed during development.",
    "Probably shouldn't be used in production.",
    "Production? What's that?",
    "Insert bug here.",
    "Have you tried turning it off and on again?",

    "Certified Open Source™ nonsense.",
    "Made with 100% locally sourced code.",
    "Now with 37% more questionable architecture.",
    "A feature-rich solution to a problem I invented.",
    "Why use a library when you can reinvent it?",
    "Why use an existing OS when you can make one?",
    "Because I can.",
    "Built from scratch, mostly because I was bored.",
    "Somewhere between genius and technical debt.",
    "The documentation is a work of fiction.",

    "Please report bugs. I need entertainment.",
    "If you understand the code, congratulations.",
    "If you don't understand the code, neither do I.",
    "There are no bugs. Only undocumented features.",
    "Everything is under control. Probably.",
    "This project has seen things.",
    "The code has become self-aware. Send help.",
    "It knows what you did.",
    "Do not feed after midnight.",
    "May or may not summon a demon.",

    "Compiled locally. Spiritually compiled elsewhere.",
    "Runs on Linux and pure spite.",
    "Tested with scientific levels of guessing.",
    "Zero guarantees. Infinite confidence.",
    "Built with love and mild frustration.",
    "Another day, another segmentation fault.",
    "Just one more feature™.",
    "The feature creep is now the feature.",
    "It started simple. It did not remain simple.",
    "Welcome to the rabbit hole."
];

document.querySelectorAll('.project p').forEach((el) => {
    el.innerHTML += "<br><i>" + descriptions[Math.floor(Math.random() * descriptions.length)] + "</i>";
});
